version: '3'

services:

    app:
        build: .
        container_name: microservice-videos-app
        # restart: always
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        # restart: always
        container_name: microservice-videos-nginx
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        # image: mysql:5.7
        # restart: always
        container_name: microservice-videos-db
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=code_micro_videos
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        # restart: always
        container_name: microservice-videos-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge