version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    # command: start-dev
    ports:
      - 8081:8080
    environment:
      # - KEYCLOAK_ADMIN=admin
      # - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2