name: ci-golang-workflow
on: [push]
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkou@v2
      - uses: actions/setup-go@2
        with:
          go-version: 1.19