name: ci-desafio
on: [pull_request]

jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd full_cycle/ci/desafio01 && npm ci
      - run: cd full_cycle/ci/desafio01 && npm test