name: ci-golang-workflow
on: [push]
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: cd full_cycle/ci/ && go test 
      - run: go run full_cycle/ci/math.go
