name: ci-golang-workflow
on: [push]

jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: cd full_cycle/ci/ && go test 
      - run: go run full_cycle/ci/math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ teste_ci_go.secrets.DOCKERHUB_USERNAME }}
          password: ${{ teste_ci_go.secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./full_cycle/ci/
          push: true
          tags: cayque16/teste_ci_go:latest
