name: ci-golang-workflow
on: [push]
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go test ./full_cycle/ci/
      - run: go run ./full_cycle/ci/math.go